/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class App {
    private final String url = "jdbc:postgresql://ec2-54-246-96-76.eu-west-1.compute.amazonaws.com:5432/dcf1hk16blmlui?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory";
    private final String user = "xvrzrkiyzpegoq";
    private final String password = "4c66fa773677847dc741725a4a411aa42790c73f4d8f057b77e4ab4c4b9cfc67";
    
    public Connection connect() {
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(url, user, password);
            System.out.println("Connected to the PostgreSQL server successfully.");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
 
        return conn;
    }
    
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        App app = new App();
        app.connect();
    }
}
